### ISSUE TITLE
Callback breaks if the video takes a while to encode

### ISSUE THREAD

**Issue by geneotech** [mtsznowak/screen-capture#2]
Sometimes it takes a while for the ``gst-launcher`` to encode the output video, and it breaks the completion callback if it requires the file to be correct, e.g. for instant replay in ``mpv``.

Can't we somehow block until encoding is complete?

**Comment by mtsznowak** [comment]
Maybe the script should block on `gst-launch` instead of `draw_line`?
The second idea is to use this: https://stackoverflow.com/questions/17894720/kill-a-process-and-wait-for-the-process-to-exit

**Comment by geneotech** [comment]
Fixed.
